/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TYPES_H_RPCGEN
#define _TYPES_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct Wspolrzedne {
	int x;
	int y;
};
typedef struct Wspolrzedne Wspolrzedne;
#ifdef __cplusplus
extern "C" bool_t xdr_Wspolrzedne(XDR *, Wspolrzedne*);
#elif __STDC__
extern  bool_t xdr_Wspolrzedne(XDR *, Wspolrzedne*);
#else /* Old Style C */
bool_t xdr_Wspolrzedne();
#endif /* Old Style C */


typedef char *tekst;
#ifdef __cplusplus
extern "C" bool_t xdr_tekst(XDR *, tekst*);
#elif __STDC__
extern  bool_t xdr_tekst(XDR *, tekst*);
#else /* Old Style C */
bool_t xdr_tekst();
#endif /* Old Style C */


typedef struct {
	u_int tablica_dynamiczna_len;
	int *tablica_dynamiczna_val;
} tablica_dynamiczna;
#ifdef __cplusplus
extern "C" bool_t xdr_tablica_dynamiczna(XDR *, tablica_dynamiczna*);
#elif __STDC__
extern  bool_t xdr_tablica_dynamiczna(XDR *, tablica_dynamiczna*);
#else /* Old Style C */
bool_t xdr_tablica_dynamiczna();
#endif /* Old Style C */


#endif /* !_TYPES_H_RPCGEN */
