/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "types.h"

bool_t
xdr_Wspolrzedne(xdrs, objp)
	XDR *xdrs;
	Wspolrzedne *objp;
{

	if (!xdr_int(xdrs, &objp->x))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->y))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_tekst(xdrs, objp)
	XDR *xdrs;
	tekst *objp;
{

	if (!xdr_string(xdrs, objp, 100))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_tablica_dynamiczna(xdrs, objp)
	XDR *xdrs;
	tablica_dynamiczna *objp;
{

	if (!xdr_array(xdrs, (char **)&objp->tablica_dynamiczna_val, (u_int *)&objp->tablica_dynamiczna_len, ~0, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	return (TRUE);
}
